### ISSUE TITLE
Proprietary icons don't work?

### ISSUE THREAD

**Issue by simonechecchia** [bderenzo/tinyhome#6]
Hi,
Is it normal that if I put a "branded" icon, such as docker, instagram or reddit, on the awesome font site, nothing is shown?
(if I insert an icon for example "film" it works)
thanks, this repo is so cool!

**Comment by bderenzo** [comment]
Hi @techkek, 
Yes it's normal, branded icons are not included in the repo.  
But if you want to use it, you have to:
* download and extract the [full font-awesome pack](https://use.fontawesome.com/releases/v5.15.3/fontawesome-free-5.15.3-web.zip)
* put the content of archive webfonts folder in repository webfonts folder
* put all.min.css of archive css folder in repository css folder and rename it fa.min.css

**Comment by simonechecchia** [comment]
unfortunately it didn't work, this is my current code:
https://github.com/techkek/tinyhome

**Comment by bderenzo** [comment]
Indeed,

**Comment by bderenzo** [comment]
Indeed, you have to add this after line 22 in `tinyhome` script:
```
     elif [ "${category}" = 'brand' ]; then
        url="$(get_element '4-' "${line}")"
        echo "<a class='card' href='${url}'><i class='fab fa-${icon}'></i>${name}</a>"
```
And then use `brand` instead of `item` as element in your `config.csv`

**Comment by simonechecchia** [comment]
now I see this:
![Screenshot_20210623_004844](https://user-images.githubusercontent.com/62959575/123009388-e426ea00-d3bc-11eb-94c9-44320981af61.png)

**Comment by bderenzo** [comment]
Weird, you current code works for me.

![capture](https://user-images.githubusercontent.com/4706149/123042348-f9b90580-d3f6-11eb-962a-7abe0347b778.png)

**Comment by simonechecchia** [comment]
thanks, I don't know why but from the pc it looked like this, I tried from another device and it works! thank you very much

**Comment by Deeoon** [comment]
Hi,
I wanted to know if it was possible to give me the HTML code working with the brand logos? I can't get the script to work and the HTML document doesn't allow to put brand logos.
Thanks in advance
